data_lakehouse_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      user: "{{ env_var('POSTGRES_USER', 'lakehouse') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'lakehouse') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'lakehouse') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0
