from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st


DASHBOARD_ROOT = Path(__file__).resolve().parents[1]
if str(DASHBOARD_ROOT) not in sys.path:
    sys.path.insert(0, str(DASHBOARD_ROOT))

from components.cards import metric_grid
from components.charts import render_count_chart, render_small_table
from components.layout import render_footer, render_header, render_sidebar, section_header, setup_page
from components.loaders import load_catalog, load_lineage, load_lineage_edges


setup_page("Metadata And Lineage")
render_sidebar("Metadata And Lineage")
render_header(
    "Metadata And Lineage",
    "Governance evidence for dataset ownership, criticality, downstream usage, and source-to-gold lineage.",
)

catalog = load_catalog()
lineage = load_lineage()
edges = load_lineage_edges()
nodes = lineage.get("nodes", []) if isinstance(lineage, dict) else []

metric_grid(
    [
        ("Catalog Entries", len(catalog), "Generated dataset catalog rows"),
        ("Lineage Nodes", len(nodes), "Nodes in local lineage graph artifact"),
        ("Lineage Edges", len(edges), "Edges in local lineage graph artifact"),
        ("Tier 1 Datasets", int((catalog.get("criticality_tier") == "tier_1").sum()) if not catalog.empty and "criticality_tier" in catalog else 0, "Critical datasets in catalog"),
    ],
    columns=4,
)

left, right = st.columns(2)
with left:
    render_count_chart(catalog, "criticality_tier", "Catalog Criticality")
with right:
    render_count_chart(catalog, "owner", "Dataset Owners")

section_header("Dataset Catalog", "Ownership, layer, source system, refresh cadence, criticality, and downstream usage.")
render_small_table(
    catalog,
    [
        "dataset_name",
        "layer",
        "owner",
        "source_system",
        "last_refresh",
        "refresh_frequency",
        "criticality_tier",
        "business_description",
        "downstream_usage",
    ],
    height=420,
)

section_header("Source-To-Gold Lineage", "Lineage graph edges generated by the local platform run.")
render_small_table(edges, height=420)

with st.expander("Lineage graph summary", expanded=False):
    st.json({"generated_at": lineage.get("generated_at"), "node_count": lineage.get("node_count", len(nodes)), "edge_count": lineage.get("edge_count", len(edges))})

render_footer()
