from __future__ import annotations

import pandas as pd
import streamlit as st

from components.cards import metric_grid, status_badge
from components.charts import render_bar_chart, render_count_chart, render_small_table
from components.layout import section_header
from components.loaders import (
    load_alerts,
    load_pipeline_summary,
    load_quality_summary,
    load_readiness,
    load_release_gates,
    load_source_freshness,
    load_trust_scores,
)


def _percent(numerator: int | float, denominator: int | float) -> str:
    if not denominator:
        return "n/a"
    return f"{(float(numerator) / float(denominator)) * 100:.0f}%"


def _mean_score(frame: pd.DataFrame) -> str:
    if frame.empty or "trust_score_overall" not in frame:
        return "n/a"
    values = pd.to_numeric(frame["trust_score_overall"], errors="coerce").dropna()
    if values.empty:
        return "n/a"
    return f"{values.mean():.1f}"


def render_data_health() -> None:
    readiness = load_readiness()
    trust = load_trust_scores()
    alerts = load_alerts()
    quality = load_quality_summary()
    freshness = load_source_freshness()
    release, gates = load_release_gates()
    pipeline_summary = load_pipeline_summary()

    total_datasets = len(readiness) if not readiness.empty else len(trust)
    healthy = int((readiness.get("readiness_status") == "ready").sum()) if not readiness.empty else 0
    at_risk = int((readiness.get("readiness_status") == "at_risk").sum()) if not readiness.empty else 0
    blocked = int((readiness.get("readiness_status") == "blocked").sum()) if not readiness.empty else 0
    freshness_pass = int((readiness.get("freshness_status") == "passed").sum()) if not readiness.empty else 0
    quality_pass = int((quality.get("quality_status", quality.get("status")) == "passed").sum()) if not quality.empty else 0
    open_alerts = int((alerts.get("resolution_status") == "open").sum()) if not alerts.empty else 0
    release_status = release.get("release_status") or pipeline_summary.get("release_status", "unknown")

    metric_grid(
        [
            ("Datasets Monitored", total_datasets, "Gold datasets with generated readiness or trust records"),
            ("Healthy Datasets", healthy, "Readiness status is ready"),
            ("At Risk", at_risk, "Datasets requiring review before BI use"),
            ("Blocked", blocked, "Datasets blocked at readiness level"),
            ("Avg Trust Score", _mean_score(trust), "Mean trust score from observability output"),
            ("Freshness Pass Rate", _percent(freshness_pass, total_datasets), "Readiness freshness status pass rate"),
            ("Quality Pass Rate", _percent(quality_pass, len(quality)), "Quality report pass rate"),
            ("Open Alerts", open_alerts, "Alerts with open resolution status"),
            ("Gold Ready For BI", healthy, "Gold datasets ready for local BI consumption"),
            ("Latest Release", release_status, "Latest local release gate status"),
        ],
        columns=5,
    )

    st.markdown(f"**Current release gate:** {status_badge(release_status)}", unsafe_allow_html=True)

    left, right = st.columns((1.2, 1))
    with left:
        section_header("Dataset Readiness Summary", "Gold datasets evaluated for quality, freshness, schema state, and row availability.")
        render_small_table(
            readiness,
            [
                "dataset_name",
                "row_count",
                "quality_status",
                "freshness_status",
                "schema_status",
                "readiness_score",
                "readiness_status",
            ],
            height=330,
        )
    with right:
        render_bar_chart(trust, "dataset_name", "trust_score_overall", "Trust Score By Dataset")

    left, right = st.columns(2)
    with left:
        render_count_chart(gates, "status", "Release Gate Status Summary")
    with right:
        render_count_chart(alerts, "severity", "Recent Alert Severity")

    section_header("Source Health", "Freshness records generated from local source load logs.")
    render_small_table(
        freshness,
        ["source_system", "layer", "last_load_time", "row_count", "schema_version", "freshness_status"],
        height=260,
    )

    section_header("Recent Alerts", "Operational signals generated by local validation, freshness, schema, and release checks.")
    render_small_table(
        alerts.sort_values("timestamp", ascending=False).head(10) if not alerts.empty and "timestamp" in alerts else alerts,
        ["timestamp", "severity", "alert_type", "dataset_name", "source_system", "business_impact", "recommended_action", "resolution_status"],
        height=300,
    )
